name: CI - Security Scan

on: [push, pull_request]

jobs:
  sast:
    runs-on: ubuntu-latest
    name: Static Analysis with Bandit
    steps:
      - name: Получить код проекта
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Установить зависимости
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install bandit

      - name: Запустить Bandit (анализ безопасности)
        run: bandit app.py
